=== Blacktoviche/PageraExam/ExamSchema/ExamSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
            xmlns:pageraexam="http://www.pagera.i8.com"
            targetNamespace="http://www.pagera.i8.com"
            elementFormDefault="qualified">

  <element name="exam" type="pageraexam:exam"/>

  <complexType name="exam">
    <sequence>
      <element name="name"  type="string"/>
      <element name="time" type="int"/>
      <element name="questionscount" type="int" minOccurs="1"
      maxOccurs="unbounded" />
      <element name="average" type="int" minOccurs="1"
       maxOccurs="unbounded"/>
      <element name="question" type="pageraexam:question" minOccurs="1"
      maxOccurs="unbounded"/>
      <element name="writer" type="pageraexam:writer"/>
    </sequence>
  </complexType>


  <complexType name="question">
    <sequence>
      <element name="questionstring" type="string"/>
      <element name="mode" type="string"/>
      <element name="answerscount" type="int" minOccurs="1"
      maxOccurs="unbounded" />
      <element name="note" type="string"/>
      <element name="answer" type="pageraexam:answer"
      minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
  </complexType>



  <complexType name="answer">
    <sequence>
      <element name="state" type="boolean"/>
      <element name="answerstring" type="string"/>
    </sequence>
  </complexType>
  <complexType name="writer">
    <sequence>
      <element name="wname" type="string"/>
      <element name="mail" type="string"/>
      <element name="webaddress" type="string"/>
      <element name="description" type="string"/>
    </sequence>
  </complexType>
</schema>

=== Blacktoviche/PageraExam/Exams/eee.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><exam xmlns="http://www.pagera.i8.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pagera.i8.com ExamSchema.xsd"><name>eee</name><time>10</time><questionscount>2</questionscount><average>20</average><question><questionstring>sssss</questionstring><mode>single</mode><answerscount>2</answerscount><note/><answer><state>true</state><answerstring>sss</answerstring></answer><answer><state>false</state><answerstring>wwwwwwwwwww</answerstring></answer></question><question><questionstring>wwwwwwwwwwwww</questionstring><mode>single</mode><answerscount>2</answerscount><note/><answer><state>true</state><answerstring>eeeeeeeeeeeeee</answerstring></answer><answer><state>false</state><answerstring>wwwwwwwww</answerstring></answer></question><writer><wname/><mail/><webaddress/><description/></writer></exam>

=== Blacktoviche/PageraExam/Exams/TestJCP.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><exam xmlns="http://www.pagera.i8.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pagera.i8.com ExamSchema.xsd"><name>TestJCP</name><time>120</time><questionscount>3</questionscount><average>72</average><question><questionstring>What is your name?</questionstring><mode>multi</mode><answerscount>3</answerscount><note/><answer><state>true</state><answerstring>Mike	</answerstring></answer><answer><state>true</state><answerstring>Malek</answerstring></answer><answer><state>false</state><answerstring>Boo</answerstring></answer></question><question><questionstring>What is your hair color?</questionstring><mode>single</mode><answerscount>2</answerscount><note/><answer><state>false</state><answerstring>Brown</answerstring></answer><answer><state>true</state><answerstring>Dark</answerstring></answer></question><question><questionstring>Bla Bla</questionstring><mode>single</mode><answerscount>2</answerscount><note/><answer><state>true</state><answerstring>bla1</answerstring></answer><answer><state>false</state><answerstring>bla2</answerstring></answer></question><writer><wname>Mike</wname><mail/><webaddress/><description/></writer></exam>
